/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_trust_rxjavademo_ndk_JniTest */

#ifndef _Included_com_trust_rxjavademo_ndk_JniTest
#define _Included_com_trust_rxjavademo_ndk_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_trust_rxjavademo_ndk_JniTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_trust_rxjavademo_ndk_JniTest_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_trust_rxjavademo_ndk_JniTest
 * Method:    updateFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_trust_rxjavademo_ndk_JniTest_updateFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_trust_rxjavademo_ndk_JniTest
 * Method:    updateIntArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_trust_rxjavademo_ndk_JniTest_updateIntArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
